spring.application.name=taxi-backend
server.port=8080
server.address=0.0.0.0

# H2 mémoire — local seulement
spring.datasource.url=jdbc:h2:mem:taxidb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

jwt.secret=nck-taxi-secret-key-2024-very-long-secret-must-be-256bits
jwt.expiration=86400000